{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust",
    "module": "go-trust-sdk-android",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.4.aar",
          "url": "go-trust-sdk-android-1.0.4.aar",
          "size": 1528437,
          "sha512": "263131be7bb77da361b44f290b45209f5fea4c0dccfce1691bdd650431051dfdd975be47066221417ca8f4a11b7d30a614b9467e7c3fb898c2108a376f200733",
          "sha256": "4db8e482ccb445f3097f470efee03317584aa2bae8cabfb604dee831e5753fbd",
          "sha1": "03ff4ec9b24cd1ccd9fcbe7b21ad0c72a960e5c0",
          "md5": "776dea258c593cbd8bb6f147fffed779"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.23.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.4.aar",
          "url": "go-trust-sdk-android-1.0.4.aar",
          "size": 1528437,
          "sha512": "263131be7bb77da361b44f290b45209f5fea4c0dccfce1691bdd650431051dfdd975be47066221417ca8f4a11b7d30a614b9467e7c3fb898c2108a376f200733",
          "sha256": "4db8e482ccb445f3097f470efee03317584aa2bae8cabfb604dee831e5753fbd",
          "sha1": "03ff4ec9b24cd1ccd9fcbe7b21ad0c72a960e5c0",
          "md5": "776dea258c593cbd8bb6f147fffed779"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.4-sources.jar",
          "url": "go-trust-sdk-android-1.0.4-sources.jar",
          "size": 277079,
          "sha512": "37e3371fea04dfcd2b93d16bfc3c0c8957df38ed32ec4a9cd37aaa9034aa4af241b02363419d23d4e18467511960694bc9d904dec2e33a89e8f5f3f967387ff2",
          "sha256": "a6b3d900e8c633a35973e5f7aedc659ca6d5ac28412c2ae4b0422ba89acc6d7e",
          "sha1": "00dc865cfa019b5a9a552bbcf66bba435f25e3f6",
          "md5": "6a49a1cb0584f987c8707c316be18c08"
        }
      ]
    }
  ]
}
