{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_debug",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.5.aar",
          "url": "file_picker_debug-1.0.5.aar",
          "size": 42488,
          "sha512": "ee410219ecbd5e4ec7cc34d9237cc97bc389a58f3640dd2bc5a5d95925c53c2d5bf9583253a0743c6360991dd1b0a71e8803de3b5abdd87d463e1b5b9903e093",
          "sha256": "7410a776b9c7df960c7c28218ed94d3f13cbc9ad6f499984c5dca584b86f6938",
          "sha1": "439bf5828506af67d5c8c7ba7c7a980b361801c5",
          "md5": "b986d640fcbddd795c7ac9a78750fd5a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.5.aar",
          "url": "file_picker_debug-1.0.5.aar",
          "size": 42488,
          "sha512": "ee410219ecbd5e4ec7cc34d9237cc97bc389a58f3640dd2bc5a5d95925c53c2d5bf9583253a0743c6360991dd1b0a71e8803de3b5abdd87d463e1b5b9903e093",
          "sha256": "7410a776b9c7df960c7c28218ed94d3f13cbc9ad6f499984c5dca584b86f6938",
          "sha1": "439bf5828506af67d5c8c7ba7c7a980b361801c5",
          "md5": "b986d640fcbddd795c7ac9a78750fd5a"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_debug-1.0.5-sources.jar",
          "url": "file_picker_debug-1.0.5-sources.jar",
          "size": 11292,
          "sha512": "6934d3e4ab9146e349471a11c4f53b19c742f677cc6686d21de93fc497534f73274b86e3f3ec2303f419ca4cb2638caf9e5782949925841b4aa329b9e5633a95",
          "sha256": "567c8d84a2aa6a6032316f8f491b21a5dcc23ab386f5b0cf333bb277b17db94d",
          "sha1": "050e0893e7be2da532a4ce3159e11ef66b30656a",
          "md5": "e74f61a98f12b510bc51302606a05d86"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_debug-1.0.5-javadoc.jar",
          "url": "file_picker_debug-1.0.5-javadoc.jar",
          "size": 307531,
          "sha512": "98f4f8506433f283842d74592bd709ab9b075e1ec8ba01c7e2764a882c92fcfb736d4059e187c6d7a7fac646b5af91086ce8563670ebcdd01ad13975d5988930",
          "sha256": "3608ff79f57253b694921fecdaade7ee97a1a6ea2f9e0683fa18073fe3343bf3",
          "sha1": "76e76b1367d8652a14bfc0e430836fab828e71a4",
          "md5": "01ce66aba1733b59440d680b123f5cb3"
        }
      ]
    }
  ]
}
