{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_release",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.7.aar",
          "url": "file_picker_release-1.0.7.aar",
          "size": 40191,
          "sha512": "cc63744b69e9e3511f7da1e9b8ff8ae84aa5a64b67105513c5ad923fad2c3be9693010a83e20836dd2c8c1478a6b785b8f1ba418cbc9c5574625932e6757904b",
          "sha256": "a3a4a59461db6c674a7f1e5597a785571c8ff2a143e4b7a0820dfce78d3246b0",
          "sha1": "24a0ed5cf6dea9cb43b32935581136fa3f654f46",
          "md5": "19446104063e8ee6c69d90afe79d9a11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.7.aar",
          "url": "file_picker_release-1.0.7.aar",
          "size": 40191,
          "sha512": "cc63744b69e9e3511f7da1e9b8ff8ae84aa5a64b67105513c5ad923fad2c3be9693010a83e20836dd2c8c1478a6b785b8f1ba418cbc9c5574625932e6757904b",
          "sha256": "a3a4a59461db6c674a7f1e5597a785571c8ff2a143e4b7a0820dfce78d3246b0",
          "sha1": "24a0ed5cf6dea9cb43b32935581136fa3f654f46",
          "md5": "19446104063e8ee6c69d90afe79d9a11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_release-1.0.7-sources.jar",
          "url": "file_picker_release-1.0.7-sources.jar",
          "size": 12004,
          "sha512": "d891079951e3f5039c955661b5c4d67178bdf623fb94715c43dcf53bca6512e701e87beead9bf5e9ef8ca176be7121c557d4788c7e17e69ca005c82420545000",
          "sha256": "605b3a46318b53258025d24cf202105a265c2488947865cdbcec8edb523f02ce",
          "sha1": "7fa8bb096c15ef66959c2087570920b7df2fd486",
          "md5": "b201810274cacc0050ca635298c99721"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_release-1.0.7-javadoc.jar",
          "url": "file_picker_release-1.0.7-javadoc.jar",
          "size": 307985,
          "sha512": "a38ae2beed9f7dc1cfa81ec75b21c5998c8d119b9985169a1f070ee351eee1ff4952fa04670686f86bac3fb1a22c406a4b67165af957fb78da534262be128bdb",
          "sha256": "8cad68744c4fd54dc0728b23cc31c05acc474cf52f8961ee5b1ad10199bd0f89",
          "sha1": "84a2ea19406ff77d025d779633b2c732af8dec57",
          "md5": "5363a2875e83d58dd7ff8986e53cd340"
        }
      ]
    }
  ]
}
