{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.3.aar",
          "url": "url_launcher_android_profile-1.0.3.aar",
          "size": 23502,
          "sha512": "0edcfcac81798436742a1478c3f0ee0e3cc1474d3437ba70ba36617c27e51c578f38bb357bbecca50a74ebed32b5004c21ca5a3535f1c67c0258436d53af3598",
          "sha256": "9104ce85993db75f2870999aed34aff96cbdef276f44b59935a649582519a642",
          "sha1": "f38c9d507363a3fc57aabe623f868a0ac4e88799",
          "md5": "3b0488aa28375cad86fa908df9889151"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.3.aar",
          "url": "url_launcher_android_profile-1.0.3.aar",
          "size": 23502,
          "sha512": "0edcfcac81798436742a1478c3f0ee0e3cc1474d3437ba70ba36617c27e51c578f38bb357bbecca50a74ebed32b5004c21ca5a3535f1c67c0258436d53af3598",
          "sha256": "9104ce85993db75f2870999aed34aff96cbdef276f44b59935a649582519a642",
          "sha1": "f38c9d507363a3fc57aabe623f868a0ac4e88799",
          "md5": "3b0488aa28375cad86fa908df9889151"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.3-sources.jar",
          "url": "url_launcher_android_profile-1.0.3-sources.jar",
          "size": 9313,
          "sha512": "992d095df67d1b653b20de471d38ae483e298811f5bb470cad4d7ffabf553451e168e5d3ac4a9593280f6983d74eb27dfafd8ced6d70da574dc2e5648944693c",
          "sha256": "1fe028244b497b0578b3df86209499fe63afee2bba459df71d15f0cc0f3f149c",
          "sha1": "888b3d3e9e6424ca726c49ce44266330d9a165c5",
          "md5": "1e4a34aa65b526add66b2064c8175c7e"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.3-javadoc.jar",
          "url": "url_launcher_android_profile-1.0.3-javadoc.jar",
          "size": 332766,
          "sha512": "be506098ea1fe1a46ce13d96a1917b0573c6ef6ccb60c9594ba65986577fbcf698239e4bd5b62e152d54d6efe6ae7aae75f6ff8c0df6eb0fd180fcce97f53b29",
          "sha256": "6eb24a38877a315a4b119b6ec9e621d0157af48f8fffff057b39b8d8767c043c",
          "sha1": "ea58679032ba6b0313140c223e8eef2469d003c8",
          "md5": "abeba0baeaf36238028ff4c034651546"
        }
      ]
    }
  ]
}
