{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_debug",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.2.aar",
          "url": "shared_preferences_android_debug-1.0.2.aar",
          "size": 112745,
          "sha512": "f290d43bddec49e637b1209115a2d653c1e412844a67fa706223a553bbdd77c21827818df70c91b99c2f18eea351ca62b2b942b6b327ac158fade9ad99d9e54c",
          "sha256": "3d1f02677d209bd0e36f0e3403209bb1063b6a97b23c61bee7d54fcaea49e871",
          "sha1": "1aeeca33fc9b6b8593dc2b9de66b9da57e9a33ef",
          "md5": "1620a43a29117df23215b6a86b64ca30"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.2.aar",
          "url": "shared_preferences_android_debug-1.0.2.aar",
          "size": 112745,
          "sha512": "f290d43bddec49e637b1209115a2d653c1e412844a67fa706223a553bbdd77c21827818df70c91b99c2f18eea351ca62b2b942b6b327ac158fade9ad99d9e54c",
          "sha256": "3d1f02677d209bd0e36f0e3403209bb1063b6a97b23c61bee7d54fcaea49e871",
          "sha1": "1aeeca33fc9b6b8593dc2b9de66b9da57e9a33ef",
          "md5": "1620a43a29117df23215b6a86b64ca30"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.2-sources.jar",
          "url": "shared_preferences_android_debug-1.0.2-sources.jar",
          "size": 13492,
          "sha512": "0377f133f27b75dad7d481bd64c572188345c170cc06df6b1eee48f43f484eaa8f2c8f11b5bef9d4619fe58f13f5af435ecb61ffcd5ac8f2907138e4062a5370",
          "sha256": "04855ff04ad7b1cab4ff55a1c032f4ad03d2c6cdac874cd77a52bfcd84be28f0",
          "sha1": "016b78521fecb132c60d480ffe43b678f71cb7d3",
          "md5": "faf6c46c05c5f8735e1343e903bb5c4e"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.2-javadoc.jar",
          "url": "shared_preferences_android_debug-1.0.2-javadoc.jar",
          "size": 356152,
          "sha512": "6d2cf62163c0aa9718eb88d28d81a3c2826656a69ed6d18df0f5822e21fb62908d62290ba6890f9429b180cb3c79bb99297c6e0399a45e69cf7b79cbd6dbe891",
          "sha256": "dcc28d2791fa11ab34fb32322ed26d411bc8eec78cb147bf119d2a9bce8b8939",
          "sha1": "f58e5d55cb6320bd22a8692f72a58c67bc8fddb2",
          "md5": "cee42dc74c59a7de95ef5d9b47ef10f5"
        }
      ]
    }
  ]
}
