{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust.consentmobilesdk",
    "module": "flutter_release",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.7.aar",
          "url": "flutter_release-1.0.7.aar",
          "size": 11262203,
          "sha512": "a8835b0832d92fb94a53cfd33506d32fa41086a4252a1e2358b89d238ec44734fa109b13cbc34c0cc50140d9f30d66b2847e3fd68d1cea070cffde285d8e6b5c",
          "sha256": "e49636309d8fecf4e1e066a10d02b65a13dad07d02c0bc828a33df6f63c5db40",
          "sha1": "9142c10410a781b7fc98cfd75a79dc1fb8dfb803",
          "md5": "75d320d171728cea3a34a00c85eda210"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.7.aar",
          "url": "flutter_release-1.0.7.aar",
          "size": 11262203,
          "sha512": "a8835b0832d92fb94a53cfd33506d32fa41086a4252a1e2358b89d238ec44734fa109b13cbc34c0cc50140d9f30d66b2847e3fd68d1cea070cffde285d8e6b5c",
          "sha256": "e49636309d8fecf4e1e066a10d02b65a13dad07d02c0bc828a33df6f63c5db40",
          "sha1": "9142c10410a781b7fc98cfd75a79dc1fb8dfb803",
          "md5": "75d320d171728cea3a34a00c85eda210"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.7-sources.jar",
          "url": "flutter_release-1.0.7-sources.jar",
          "size": 1283,
          "sha512": "9096af4c9f50e404d7af5fef6a618c285c28755cf324a301925474f4f41d66de1911ec65eaeacad6dcee1e8f24d997083af77f3fdee964526462397e5043855f",
          "sha256": "8cf1c8b85b788f7cd8942a12d0bfcacef979a19914a3403385586f7a43556009",
          "sha1": "e00e93aeeb733f8cf82b07799a9fab599e67d03f",
          "md5": "4af78276d48ae8c3487ba6fb7d70f500"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.7-javadoc.jar",
          "url": "flutter_release-1.0.7-javadoc.jar",
          "size": 261621,
          "sha512": "d645c8ade8cff2fe365386a0cf323bbf0938150bb602383242b25e33e051ebfa22de5038d591d464204e7f48a49f9b5e3da8b6a7e5684801f4ac15289fc5b068",
          "sha256": "16518c2f23ab25ac23fec19fcb974f9684e4d4b38141e75e61df5a3b3593cac2",
          "sha1": "321cd4dcca69ed70ca60dd594e7a7fa0810a75da",
          "md5": "0aeab8977ecce7d5cf6d8e2aba5dab37"
        }
      ]
    }
  ]
}
