{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_profile",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.2.aar",
          "url": "file_picker_profile-1.0.2.aar",
          "size": 42485,
          "sha512": "90202cb0635029018b4023221e339ba677b063424ce200ea39f4d447d38cdf8beb2f78dd448476f59de30e69a72e3a6448887fccf8c026b6962605e560a5d701",
          "sha256": "c7842e08b85488506ded6ed8e5306a9b61610208884688a45223c58491219e96",
          "sha1": "60bddc7576ef79b8a43bb586eac976c7d8554053",
          "md5": "0db5576970d65f2051f728e43305041d"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.2.aar",
          "url": "file_picker_profile-1.0.2.aar",
          "size": 42485,
          "sha512": "90202cb0635029018b4023221e339ba677b063424ce200ea39f4d447d38cdf8beb2f78dd448476f59de30e69a72e3a6448887fccf8c026b6962605e560a5d701",
          "sha256": "c7842e08b85488506ded6ed8e5306a9b61610208884688a45223c58491219e96",
          "sha1": "60bddc7576ef79b8a43bb586eac976c7d8554053",
          "md5": "0db5576970d65f2051f728e43305041d"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_profile-1.0.2-sources.jar",
          "url": "file_picker_profile-1.0.2-sources.jar",
          "size": 11292,
          "sha512": "6934d3e4ab9146e349471a11c4f53b19c742f677cc6686d21de93fc497534f73274b86e3f3ec2303f419ca4cb2638caf9e5782949925841b4aa329b9e5633a95",
          "sha256": "567c8d84a2aa6a6032316f8f491b21a5dcc23ab386f5b0cf333bb277b17db94d",
          "sha1": "050e0893e7be2da532a4ce3159e11ef66b30656a",
          "md5": "e74f61a98f12b510bc51302606a05d86"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_profile-1.0.2-javadoc.jar",
          "url": "file_picker_profile-1.0.2-javadoc.jar",
          "size": 307526,
          "sha512": "5e953f4c631e4892d72ab36bcc2b21ee20702bcd2bc6772c282408777e0af09d2c7db12eda333b801c4a7394b55d0b8f7c77d77e59c1b0ab012362be136c6850",
          "sha256": "86604ff062b960f76251080b920a4f8ba86ca313d30007043cb2ee0f2e91fa85",
          "sha1": "e17d8433a752848f73561a006ad9a1ab047fdcd2",
          "md5": "3a250b81c96b5151e9593e8465a99f30"
        }
      ]
    }
  ]
}
