{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_profile",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.9.aar",
          "url": "file_picker_profile-1.0.9.aar",
          "size": 42465,
          "sha512": "223f14f8dbcd59b998eed5b9b258f15c40068c05d8f1073281ad557f36b4fc844e9f948be03ed296aa137f855893e13e8559393f6710830ff56c13615c7fe874",
          "sha256": "d3fe66b8b1a64fbe9a79ed56b14afc425cddde329a4c84b20ed5dc5e63b2d295",
          "sha1": "03c3f7b33df9b5fcb02273a8dc8982b47bfdca22",
          "md5": "e01e33347f1cd9358f212796b2a51b50"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.9.aar",
          "url": "file_picker_profile-1.0.9.aar",
          "size": 42465,
          "sha512": "223f14f8dbcd59b998eed5b9b258f15c40068c05d8f1073281ad557f36b4fc844e9f948be03ed296aa137f855893e13e8559393f6710830ff56c13615c7fe874",
          "sha256": "d3fe66b8b1a64fbe9a79ed56b14afc425cddde329a4c84b20ed5dc5e63b2d295",
          "sha1": "03c3f7b33df9b5fcb02273a8dc8982b47bfdca22",
          "md5": "e01e33347f1cd9358f212796b2a51b50"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_profile-1.0.9-sources.jar",
          "url": "file_picker_profile-1.0.9-sources.jar",
          "size": 12004,
          "sha512": "d891079951e3f5039c955661b5c4d67178bdf623fb94715c43dcf53bca6512e701e87beead9bf5e9ef8ca176be7121c557d4788c7e17e69ca005c82420545000",
          "sha256": "605b3a46318b53258025d24cf202105a265c2488947865cdbcec8edb523f02ce",
          "sha1": "7fa8bb096c15ef66959c2087570920b7df2fd486",
          "md5": "b201810274cacc0050ca635298c99721"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_profile-1.0.9-javadoc.jar",
          "url": "file_picker_profile-1.0.9-javadoc.jar",
          "size": 307985,
          "sha512": "74f16f1ad8644df802e046a6542492abb0067f733f0228dfaeb74b082341a336a130574f0e5d987f8a1e08526f83fa133229799f32843026cb3129705e1e44ff",
          "sha256": "3c50294a1b4b8e35da3811f662177241fffa2c25b70718bc5bddb6e64008d868",
          "sha1": "ec7b94266bbaf02e466857466a1a93b5b3fc7798",
          "md5": "8188fdf8285a6eac61be1f5cae854104"
        }
      ]
    }
  ]
}
