{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_debug",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.3.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.3.aar",
          "size": 2526,
          "sha512": "04fab3d71042813fc354e0c93cd7d82ae37fff7ae9b5b676c9006d4c290514206be04f1c83cd1c1c8a60106c1308c29b93a9218f5a65446a838229267ecaa193",
          "sha256": "57e6f44471908fd2b1a156e7ba374219dd9d757ac120814e4ab642c17a4c2e96",
          "sha1": "515176c06213bd0c5dd33ed0d517449a47f83512",
          "md5": "5f39dcc2ceb0bfb83b0af49fe93cf23b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.3.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.3.aar",
          "size": 2526,
          "sha512": "04fab3d71042813fc354e0c93cd7d82ae37fff7ae9b5b676c9006d4c290514206be04f1c83cd1c1c8a60106c1308c29b93a9218f5a65446a838229267ecaa193",
          "sha256": "57e6f44471908fd2b1a156e7ba374219dd9d757ac120814e4ab642c17a4c2e96",
          "sha1": "515176c06213bd0c5dd33ed0d517449a47f83512",
          "md5": "5f39dcc2ceb0bfb83b0af49fe93cf23b"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.3-sources.jar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.3-sources.jar",
          "size": 2659,
          "sha512": "d848b9ac3a80bd88694f7d35de2abc2866f65393d53caa1f49513063e17fe497a4b7e1ed09dc3736f529a166f1491dfb78c703a51f0fe0950082488869f2b352",
          "sha256": "2930f0a83f74dc7a57026b471c4443a3e5cb4f8b5f80bf45d161dd31675194c7",
          "sha1": "82b1c36d1af62197547e6c132ae64f520e3ad7a7",
          "md5": "fb7b3ee0458fe0f3ec0a8116c68f72ed"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.3-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.3-javadoc.jar",
          "size": 269831,
          "sha512": "d5c4839effc4700a1d2930bcb20c8f1f67b67e787ce390c5fa5388f33c007ed67887a317f27b54a5cf59350930fc76e0c655a704681bad309c547c4116aafc6a",
          "sha256": "10cb0016d7610843bcd2272b7ad757d365c755b96f2e26430b58b8f5e1b3c62e",
          "sha1": "d23993abc7cee218768879d34681d6d26db0f971",
          "md5": "64355048f3a23ccc25211e1ad96de0e8"
        }
      ]
    }
  ]
}
