{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.7.aar",
          "url": "webview_flutter_android_release-1.0.7.aar",
          "size": 266950,
          "sha512": "950027e847d7ca06dafb2ab94601dfa7f49fa012d63d900e53fd58166e53044a634b3fe3148b85816b08d4233a1786d0fd9f925c94210dcd81c448638529c9e2",
          "sha256": "3b0bb5033f3f546448220fe2cbc4b1fc1890c758dbb02ba35a9372d5c4ae53a9",
          "sha1": "68e0596d182404000b621e7d4c457deaa80c9280",
          "md5": "929970d84d46537f05391871b15b783f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.7.aar",
          "url": "webview_flutter_android_release-1.0.7.aar",
          "size": 266950,
          "sha512": "950027e847d7ca06dafb2ab94601dfa7f49fa012d63d900e53fd58166e53044a634b3fe3148b85816b08d4233a1786d0fd9f925c94210dcd81c448638529c9e2",
          "sha256": "3b0bb5033f3f546448220fe2cbc4b1fc1890c758dbb02ba35a9372d5c4ae53a9",
          "sha1": "68e0596d182404000b621e7d4c457deaa80c9280",
          "md5": "929970d84d46537f05391871b15b783f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.7-sources.jar",
          "url": "webview_flutter_android_release-1.0.7-sources.jar",
          "size": 61506,
          "sha512": "e6568ae0bc08aa93f82969eb5163670b978aa0ce9d7afad819121949388a63e6250769aff10c8aa49cb75695eb40e109a95339bf591b3c1670de27e43728cd63",
          "sha256": "89a1b253e75696a2014ff86d66e8be4957a953a2dffdc90208065efbfe52ab76",
          "sha1": "d84f5919cb52a89638e6a5bf8e86171f7b40c9e4",
          "md5": "1afcd4ba8b50bfed2f5ca86d4a89f702"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.7-javadoc.jar",
          "url": "webview_flutter_android_release-1.0.7-javadoc.jar",
          "size": 750999,
          "sha512": "0e237501792d3a2bc8325eefa2747338a7852f7fb97c2e48f60d85d7588af0174c2ef6982caf056a7f68cc9f04ea47a3a1ffacbc4c16b5ea99d9482951c86052",
          "sha256": "30c5a17d5a43e765e86b4f1adfba5dc989ad7eb12c63727bb2ade7f96ac5e9ae",
          "sha1": "23a2ef1a38a503b842ecbc3b77448b9e0f6b4587",
          "md5": "7c3cd45487a7b20607847b36598ca90c"
        }
      ]
    }
  ]
}
