{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_profile",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.1.0.aar",
          "url": "shared_preferences_android_profile-1.1.0.aar",
          "size": 114400,
          "sha512": "d8b99666a0a309f3fffd797f4b14ef12786ff4247e5626dffb0205cff90e63b180777fd5e258f7db04df55fa642428fcc51dcf73d355e13b8397d4622304860c",
          "sha256": "78c983812495891c133a15d70cb297e996d9a04707c0f135dc927cb75f462a2b",
          "sha1": "444f84a4f49e3482c659ea8be7cc991e4f185233",
          "md5": "a67ed4b794c180308f2ea6fad2f65e81"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.1.0.aar",
          "url": "shared_preferences_android_profile-1.1.0.aar",
          "size": 114400,
          "sha512": "d8b99666a0a309f3fffd797f4b14ef12786ff4247e5626dffb0205cff90e63b180777fd5e258f7db04df55fa642428fcc51dcf73d355e13b8397d4622304860c",
          "sha256": "78c983812495891c133a15d70cb297e996d9a04707c0f135dc927cb75f462a2b",
          "sha1": "444f84a4f49e3482c659ea8be7cc991e4f185233",
          "md5": "a67ed4b794c180308f2ea6fad2f65e81"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.1.0-sources.jar",
          "url": "shared_preferences_android_profile-1.1.0-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.1.0-javadoc.jar",
          "url": "shared_preferences_android_profile-1.1.0-javadoc.jar",
          "size": 358407,
          "sha512": "28bf4529da50bb93cecd5fdf4b3769afff856ac3e963a6124fdc7df99ab1a5b831f4bb6ea9d386408e816b220b91f18128e9fd59491c2ac35ff33545a13c1a0d",
          "sha256": "22a8b2faa3011e9b72eeb7c897ec766dfaa98cee985dbebeb89c467eb1c50372",
          "sha1": "3f28aa7a976fbc99eec8bed75d0ca6edd5a0b36f",
          "md5": "38bfe12348a045015202495c87f87fb4"
        }
      ]
    }
  ]
}
