{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 280928,
          "sha512": "327053d3b0ffb2ed372abb81705345ebd4c576c48f9f8a10254c0af1ddd512f8ca7dcb1f6ade4a7aa4680e3acdb39235b3206acd566350bcaf0ea64d75833954",
          "sha256": "c77fbe4a757453397d685341cea65acf5d1e699d43409807158c86d21098943f",
          "sha1": "294f7d84bd36afdfc54b5a20f88a256c942a0cae",
          "md5": "e0bbc5080d4298807eb337d92c897c69"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 280928,
          "sha512": "327053d3b0ffb2ed372abb81705345ebd4c576c48f9f8a10254c0af1ddd512f8ca7dcb1f6ade4a7aa4680e3acdb39235b3206acd566350bcaf0ea64d75833954",
          "sha256": "c77fbe4a757453397d685341cea65acf5d1e699d43409807158c86d21098943f",
          "sha1": "294f7d84bd36afdfc54b5a20f88a256c942a0cae",
          "md5": "e0bbc5080d4298807eb337d92c897c69"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0-sources.jar",
          "url": "webview_flutter_android_debug-1.0-sources.jar",
          "size": 61256,
          "sha512": "e3db1dce34c386ce779888a190e84c5f72e7dd021cacb1f763168532618a880d7ff0ee468906838adb7e42014874c9ba4f9242269b5490489992edb597961436",
          "sha256": "00584e3f73376120584215cc456a80948d2d9e252aa9b1af928063244eae7c0d",
          "sha1": "aa4fb2c895a8a19e0caae6d391614eba954d2d9c",
          "md5": "2fed686b26cea8a297d9479369d5867a"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0-javadoc.jar",
          "url": "webview_flutter_android_debug-1.0-javadoc.jar",
          "size": 750378,
          "sha512": "64fa926dfadd3b8ad80421ac5b1561b2e5429143e57e3bcd1023f97bb270927305b3a92d85f68ca99a5e80f15128b7e589e26f3d8513e3a776e9d85e2db4b429",
          "sha256": "c9298642ef85ec6bab657a3821ff9a8854b3b96de0170cdb60e7e50fc19feafe",
          "sha1": "4ae6b8d59a0d3b802655b30003f0d98ace21556f",
          "md5": "922cb25dc70bee086ef40e9da6b1fda7"
        }
      ]
    }
  ]
}
