{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.5.aar",
          "url": "url_launcher_android_profile-1.0.5.aar",
          "size": 23502,
          "sha512": "0edcfcac81798436742a1478c3f0ee0e3cc1474d3437ba70ba36617c27e51c578f38bb357bbecca50a74ebed32b5004c21ca5a3535f1c67c0258436d53af3598",
          "sha256": "9104ce85993db75f2870999aed34aff96cbdef276f44b59935a649582519a642",
          "sha1": "f38c9d507363a3fc57aabe623f868a0ac4e88799",
          "md5": "3b0488aa28375cad86fa908df9889151"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.5.aar",
          "url": "url_launcher_android_profile-1.0.5.aar",
          "size": 23502,
          "sha512": "0edcfcac81798436742a1478c3f0ee0e3cc1474d3437ba70ba36617c27e51c578f38bb357bbecca50a74ebed32b5004c21ca5a3535f1c67c0258436d53af3598",
          "sha256": "9104ce85993db75f2870999aed34aff96cbdef276f44b59935a649582519a642",
          "sha1": "f38c9d507363a3fc57aabe623f868a0ac4e88799",
          "md5": "3b0488aa28375cad86fa908df9889151"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.5-sources.jar",
          "url": "url_launcher_android_profile-1.0.5-sources.jar",
          "size": 9313,
          "sha512": "992d095df67d1b653b20de471d38ae483e298811f5bb470cad4d7ffabf553451e168e5d3ac4a9593280f6983d74eb27dfafd8ced6d70da574dc2e5648944693c",
          "sha256": "1fe028244b497b0578b3df86209499fe63afee2bba459df71d15f0cc0f3f149c",
          "sha1": "888b3d3e9e6424ca726c49ce44266330d9a165c5",
          "md5": "1e4a34aa65b526add66b2064c8175c7e"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.5-javadoc.jar",
          "url": "url_launcher_android_profile-1.0.5-javadoc.jar",
          "size": 332767,
          "sha512": "de20c04b03fa22b5bb16f435d10efe5bfe44ab65a5abb50dca4ec6a3872206aaca08105d6aa33012ff756fcb7c0e5dfa61e037a635d122d0ca2ee20599b28701",
          "sha256": "3264086315e5bd99997f19854d8d4a3077354c0a5074995b4909948a17561864",
          "sha1": "627aa087571510fe15869746ca0182077075f43a",
          "md5": "145df27235fdefb4302261a3934ea2d6"
        }
      ]
    }
  ]
}
