{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_debug",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.9.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.9.aar",
          "size": 2526,
          "sha512": "564d91556e831e173e35292e6e6b007d76222497c149c28fad8322659f203d44b7b5402329782f18510ecb925ff4bef576189ea0a631931c4e2a132e4d408bdf",
          "sha256": "3ca62ec5f7b4e892233dfc520def0ee27fed2258d4f5842b184c5c44f80f67f7",
          "sha1": "264e31a42122a29e0c4ed3a243e88c798b47a1fb",
          "md5": "bc67e8e0bc147f4dbe49d6f00c31a420"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.9.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.9.aar",
          "size": 2526,
          "sha512": "564d91556e831e173e35292e6e6b007d76222497c149c28fad8322659f203d44b7b5402329782f18510ecb925ff4bef576189ea0a631931c4e2a132e4d408bdf",
          "sha256": "3ca62ec5f7b4e892233dfc520def0ee27fed2258d4f5842b184c5c44f80f67f7",
          "sha1": "264e31a42122a29e0c4ed3a243e88c798b47a1fb",
          "md5": "bc67e8e0bc147f4dbe49d6f00c31a420"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.9-sources.jar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.9-sources.jar",
          "size": 2659,
          "sha512": "d848b9ac3a80bd88694f7d35de2abc2866f65393d53caa1f49513063e17fe497a4b7e1ed09dc3736f529a166f1491dfb78c703a51f0fe0950082488869f2b352",
          "sha256": "2930f0a83f74dc7a57026b471c4443a3e5cb4f8b5f80bf45d161dd31675194c7",
          "sha1": "82b1c36d1af62197547e6c132ae64f520e3ad7a7",
          "md5": "fb7b3ee0458fe0f3ec0a8116c68f72ed"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.9-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.9-javadoc.jar",
          "size": 269831,
          "sha512": "bfc8acfc7448e6a9091f0c66f8e324ff861bcef40e0de6bbe28d970fbaca255dfa4918c2e372f5c38261bc8eb7802f6e14f14ffc34b22d9690177a8ccbe414f9",
          "sha256": "f7b1f3dcce81672d914d66d99fab49bf43f75bffef65cb684b0d1ccdfb1c6ebb",
          "sha1": "ed5f5cded3fd05920e58636c84d5829de8c08909",
          "md5": "ca20c2616ee02c77b477db2cbf481470"
        }
      ]
    }
  ]
}
