{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust",
    "module": "go-trust-sdk-android-tv",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.gotrust",
          "module": "go-trust-sdk-android",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-tv-1.0.6.aar",
          "url": "go-trust-sdk-android-tv-1.0.6.aar",
          "size": 534353,
          "sha512": "49c98447de3a53bbe37ab4c5bafacd8d140e292684f6225f2cac5d259ecfa664ceaf0ee7b30607b121b22a93096538235c03787042ac1424a9ff786d6f5b12d2",
          "sha256": "5f073b41c75ddc6a7ed0ef7b149de49bcb79288391547440dcec3befe906ac69",
          "sha1": "4bdb760b55454bee22f2cfc5a9a273b1b2823a98",
          "md5": "a3a503b42d9aeb0a2c1448c7bfdbbeb5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "com.gotrust",
          "module": "go-trust-sdk-android",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-tv-1.0.6.aar",
          "url": "go-trust-sdk-android-tv-1.0.6.aar",
          "size": 534353,
          "sha512": "49c98447de3a53bbe37ab4c5bafacd8d140e292684f6225f2cac5d259ecfa664ceaf0ee7b30607b121b22a93096538235c03787042ac1424a9ff786d6f5b12d2",
          "sha256": "5f073b41c75ddc6a7ed0ef7b149de49bcb79288391547440dcec3befe906ac69",
          "sha1": "4bdb760b55454bee22f2cfc5a9a273b1b2823a98",
          "md5": "a3a503b42d9aeb0a2c1448c7bfdbbeb5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "go-trust-sdk-android-tv-1.0.6-sources.jar",
          "url": "go-trust-sdk-android-tv-1.0.6-sources.jar",
          "size": 105633,
          "sha512": "9bf04315627230e1cad85f4cf062c36cb6f7decff9b87a643c20ff879a2264f0c71f04357efa89a1560d99d8bb5afee1b8349a78885a76c5fe793eb1a933b4c2",
          "sha256": "3f63e1b032faf102d3d6f9a29f0d5dae86cc09f985cbcdece3ee996c676b75d6",
          "sha1": "26853f914eadb72bae30ea5fae698bc9546c0b48",
          "md5": "8b75321fa6eb96287b808d13b24e839b"
        }
      ]
    }
  ]
}
