{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust.consentmobilesdk",
    "module": "flutter_release",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.1.2.aar",
          "url": "flutter_release-1.1.2.aar",
          "size": 12015755,
          "sha512": "8c63ce31f6b5943a9214261f3b10acdf310a8a91abb78e81cef5f3e42f1dcd50a9938b74634b125b8d07dfbc3e4cafd4178166e70c923072d7886a14fcf9159c",
          "sha256": "45da482b015474d24e5e474cbec7281da9b9207469672f788966455e39936b82",
          "sha1": "2bc1eddfefa1352083f461b1be32d77f92ba12e5",
          "md5": "8fd7dfbf5d57ae5e2f2872a8291819a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.1.2.aar",
          "url": "flutter_release-1.1.2.aar",
          "size": 12015755,
          "sha512": "8c63ce31f6b5943a9214261f3b10acdf310a8a91abb78e81cef5f3e42f1dcd50a9938b74634b125b8d07dfbc3e4cafd4178166e70c923072d7886a14fcf9159c",
          "sha256": "45da482b015474d24e5e474cbec7281da9b9207469672f788966455e39936b82",
          "sha1": "2bc1eddfefa1352083f461b1be32d77f92ba12e5",
          "md5": "8fd7dfbf5d57ae5e2f2872a8291819a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.1.2-sources.jar",
          "url": "flutter_release-1.1.2-sources.jar",
          "size": 1283,
          "sha512": "9096af4c9f50e404d7af5fef6a618c285c28755cf324a301925474f4f41d66de1911ec65eaeacad6dcee1e8f24d997083af77f3fdee964526462397e5043855f",
          "sha256": "8cf1c8b85b788f7cd8942a12d0bfcacef979a19914a3403385586f7a43556009",
          "sha1": "e00e93aeeb733f8cf82b07799a9fab599e67d03f",
          "md5": "4af78276d48ae8c3487ba6fb7d70f500"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.1.2-javadoc.jar",
          "url": "flutter_release-1.1.2-javadoc.jar",
          "size": 261619,
          "sha512": "2e13989941a93b14cbee129a5e05c5b59452d2847f3a47547a8b66aa49e65ba58cc5f9c179dffaa9a1394273926e117650a2a14952312acb35e1a942eee80d2c",
          "sha256": "b647a9e8a25778d77dd4c4fd469c3c5d871e9e203df34a95cca137ee0c9da36b",
          "sha1": "9eb2356b5ffad86b6500f0da536eede5346cb223",
          "md5": "0c5bdd1deb2557ffbafe9257891039c1"
        }
      ]
    }
  ]
}
