{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust.consentmobilesdk",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 24889006,
          "sha512": "701ca67c4571ca57885cd58b34f60d8ec6f6276e72f4592f4fad50aa78a271f4bed0c01f69cfeafab3fb28d7c04dc98decc97a1c11adc6a3febbb8a63c1a6698",
          "sha256": "bab74bfdd190b1de19c56205ac427d6d7e7d70afb092b6fe0f5ec400c2a4110a",
          "sha1": "19ee48e58fd9ac68d9aeb8dd7e507e2d2cf353c9",
          "md5": "eaf9096c1f8a4a1f544d89c1e0cb2376"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 24889006,
          "sha512": "701ca67c4571ca57885cd58b34f60d8ec6f6276e72f4592f4fad50aa78a271f4bed0c01f69cfeafab3fb28d7c04dc98decc97a1c11adc6a3febbb8a63c1a6698",
          "sha256": "bab74bfdd190b1de19c56205ac427d6d7e7d70afb092b6fe0f5ec400c2a4110a",
          "sha1": "19ee48e58fd9ac68d9aeb8dd7e507e2d2cf353c9",
          "md5": "eaf9096c1f8a4a1f544d89c1e0cb2376"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-sources.jar",
          "url": "flutter_debug-1.0-sources.jar",
          "size": 1283,
          "sha512": "9096af4c9f50e404d7af5fef6a618c285c28755cf324a301925474f4f41d66de1911ec65eaeacad6dcee1e8f24d997083af77f3fdee964526462397e5043855f",
          "sha256": "8cf1c8b85b788f7cd8942a12d0bfcacef979a19914a3403385586f7a43556009",
          "sha1": "e00e93aeeb733f8cf82b07799a9fab599e67d03f",
          "md5": "4af78276d48ae8c3487ba6fb7d70f500"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-javadoc.jar",
          "url": "flutter_debug-1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
