{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.1.2.aar",
          "url": "shared_preferences_android_release-1.1.2.aar",
          "size": 108974,
          "sha512": "336608fb1ecd9928d8a9805dc6802b6ce6d9c27a552ada084ed4438f44d608b161b0ce2036657ab8c6f456f7fc08933f2f6ca069fbef3cae2fab16babfe0c08e",
          "sha256": "60b8c0298750446ddd6ca3f17562eac5b8353a7cb61a81264ccecaf3fb2fea02",
          "sha1": "2296ee9a1c2b08bdc62eb71a9d68f1c08527d931",
          "md5": "6cffbb45766441efa0da8cc23a916cbe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.1.2.aar",
          "url": "shared_preferences_android_release-1.1.2.aar",
          "size": 108974,
          "sha512": "336608fb1ecd9928d8a9805dc6802b6ce6d9c27a552ada084ed4438f44d608b161b0ce2036657ab8c6f456f7fc08933f2f6ca069fbef3cae2fab16babfe0c08e",
          "sha256": "60b8c0298750446ddd6ca3f17562eac5b8353a7cb61a81264ccecaf3fb2fea02",
          "sha1": "2296ee9a1c2b08bdc62eb71a9d68f1c08527d931",
          "md5": "6cffbb45766441efa0da8cc23a916cbe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.1.2-sources.jar",
          "url": "shared_preferences_android_release-1.1.2-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.1.2-javadoc.jar",
          "url": "shared_preferences_android_release-1.1.2-javadoc.jar",
          "size": 358408,
          "sha512": "f9c2df92f870117b5ae20b4076ef0f3a9e37ee484c1483130293d013fd68be300d0ba7ea581bb964fa4c50fd490753b5655e92ee75623a4cbd79c48741aa2b9a",
          "sha256": "080d05a5d763622a6a5133bc9b0c58415a9ea8831f1786d43ff5d85047f50b90",
          "sha1": "c90e3abf16bceef4f5b41ae4827a274446871816",
          "md5": "39be4681650aee0e04728b0ab115dc46"
        }
      ]
    }
  ]
}
