{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust",
    "module": "go-trust-sdk-android-tv",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.gotrust",
          "module": "go-trust-sdk-android",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-tv-1.0.5.aar",
          "url": "go-trust-sdk-android-tv-1.0.5.aar",
          "size": 534923,
          "sha512": "2ab6753d67041ab49fe67026a2f17282e981bd9b9638317f937f1c62f7b38c4c807daeba6e05ced39b79e54c7d1a4c3c078f02f65f024d6b8e42ba738dc526ed",
          "sha256": "3a15b55b16f7af7db5062ba25dcccf88ad8d3605afb3b5827e0923c8694127a3",
          "sha1": "e57a76c846b35c342f27f7bddc97d23a3930507b",
          "md5": "69a34be1642ec0c49cf62ed843569a67"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "com.gotrust",
          "module": "go-trust-sdk-android",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-tv-1.0.5.aar",
          "url": "go-trust-sdk-android-tv-1.0.5.aar",
          "size": 534923,
          "sha512": "2ab6753d67041ab49fe67026a2f17282e981bd9b9638317f937f1c62f7b38c4c807daeba6e05ced39b79e54c7d1a4c3c078f02f65f024d6b8e42ba738dc526ed",
          "sha256": "3a15b55b16f7af7db5062ba25dcccf88ad8d3605afb3b5827e0923c8694127a3",
          "sha1": "e57a76c846b35c342f27f7bddc97d23a3930507b",
          "md5": "69a34be1642ec0c49cf62ed843569a67"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "go-trust-sdk-android-tv-1.0.5-sources.jar",
          "url": "go-trust-sdk-android-tv-1.0.5-sources.jar",
          "size": 105485,
          "sha512": "87230a21fc62d86d1fb48e01548478a2c2d3c0522276a420ba1d5423303fb271dc8b2a64629942e62bb3a3b4fcb6fc2e88a652daeed7d083b67100eac5db47f5",
          "sha256": "67fc433ae852599e34313995ca888bd5af7cc3e8a5f7e73e92b6a19186c9b701",
          "sha1": "1e1ee704acd64faae7aa5fef95b1e5780c8ea091",
          "md5": "809330674bd9e3dc1a8c41f2e152e5c9"
        }
      ]
    }
  ]
}
