{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.7.aar",
          "url": "webview_flutter_android_profile-1.0.7.aar",
          "size": 281395,
          "sha512": "a8d7e1ee29d1e3d9f77f81b670ee1b734f0d06c3ad0c88d503cdb4408fbe9bad9e93b75553ab2763f22a30cbd12d1e27622ce0ba734ddca36eb80aa99254f161",
          "sha256": "3d758833d8fb855abc24830158f5e0197c89ff63b0a0994440a255606d6c9dcd",
          "sha1": "ae1f10569b8d3eb8f6d98c068ac219ef78049af8",
          "md5": "efef0f91cba958fa0bc7d68deb628071"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.7.aar",
          "url": "webview_flutter_android_profile-1.0.7.aar",
          "size": 281395,
          "sha512": "a8d7e1ee29d1e3d9f77f81b670ee1b734f0d06c3ad0c88d503cdb4408fbe9bad9e93b75553ab2763f22a30cbd12d1e27622ce0ba734ddca36eb80aa99254f161",
          "sha256": "3d758833d8fb855abc24830158f5e0197c89ff63b0a0994440a255606d6c9dcd",
          "sha1": "ae1f10569b8d3eb8f6d98c068ac219ef78049af8",
          "md5": "efef0f91cba958fa0bc7d68deb628071"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.7-sources.jar",
          "url": "webview_flutter_android_profile-1.0.7-sources.jar",
          "size": 61506,
          "sha512": "e6568ae0bc08aa93f82969eb5163670b978aa0ce9d7afad819121949388a63e6250769aff10c8aa49cb75695eb40e109a95339bf591b3c1670de27e43728cd63",
          "sha256": "89a1b253e75696a2014ff86d66e8be4957a953a2dffdc90208065efbfe52ab76",
          "sha1": "d84f5919cb52a89638e6a5bf8e86171f7b40c9e4",
          "md5": "1afcd4ba8b50bfed2f5ca86d4a89f702"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.7-javadoc.jar",
          "url": "webview_flutter_android_profile-1.0.7-javadoc.jar",
          "size": 751096,
          "sha512": "f7b6d64acdb0b9cf642ac3cd6eaf200875ac992eb6f166735b893993bd6aca7cc513e4575dc488be808b584fe891a3c4a5f74023103a80a9c6fecdc7edc61024",
          "sha256": "aded3b0d56f50dd04a5fb011d90727fd98367d0fe0ea4a9567b282ac74ceb48d",
          "sha1": "c59484395d96175f106c2ce4436be274aece8411",
          "md5": "02cf90bdfea4b94c38b13e1467c299c0"
        }
      ]
    }
  ]
}
