{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust",
    "module": "go-trust-sdk-android",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.6.aar",
          "url": "go-trust-sdk-android-1.0.6.aar",
          "size": 1538204,
          "sha512": "428a0db85920d14ec49d1e2ca5462c03c127de305d78d8ba704f6d2ce5431d3e5a8515462c7c4126a6204f7beff8d510213249d1a980a59ad2d65cfd7b209a39",
          "sha256": "7afb6a047bf976fa308a05239193f2237f2f719ac45f70a76460c62bc802265b",
          "sha1": "adf623356f8d48e83e4a3783daf326c3ce0bdc3b",
          "md5": "d6f9db27fd7090f58980ed8fe20b6678"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.23.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.6.aar",
          "url": "go-trust-sdk-android-1.0.6.aar",
          "size": 1538204,
          "sha512": "428a0db85920d14ec49d1e2ca5462c03c127de305d78d8ba704f6d2ce5431d3e5a8515462c7c4126a6204f7beff8d510213249d1a980a59ad2d65cfd7b209a39",
          "sha256": "7afb6a047bf976fa308a05239193f2237f2f719ac45f70a76460c62bc802265b",
          "sha1": "adf623356f8d48e83e4a3783daf326c3ce0bdc3b",
          "md5": "d6f9db27fd7090f58980ed8fe20b6678"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.6-sources.jar",
          "url": "go-trust-sdk-android-1.0.6-sources.jar",
          "size": 284163,
          "sha512": "05ce8f0e4ed26d00265a21f3d6379b2b163e608568bcd5d5144a0a41b18c159b6a646f4b6fcbcd044eca6ab3c5ef537bebefd62d641ce2275c38c15714e0e15f",
          "sha256": "8af91a10566263899f4e87b56eeeb3d3de48faca916e7640dd35e0528de3b568",
          "sha1": "7efc0faaafc6a7ffd6007df574888bdff92a31a1",
          "md5": "a6004eb0bb0ea06b77ff0d677e7ac2f7"
        }
      ]
    }
  ]
}
