{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.1.1.aar",
          "url": "device_info_plus_profile-1.1.1.aar",
          "size": 7959,
          "sha512": "0062351c9f6ece45049dfba0a1304525ca29de42398ab245359e344900c6f8191e04e1bf6880c4c660b79c40602c1ff2c5108749dbe1661fed44100756395b62",
          "sha256": "c8c98c2b9238f936aebd34a42fd1246d16ec63b98f626216bd5dbb79fc8ff062",
          "sha1": "2196e1076f63aacd9e56dfca7bc4d87abfdfc787",
          "md5": "54c9215b8bf1eee649baf096064a9433"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.1.1.aar",
          "url": "device_info_plus_profile-1.1.1.aar",
          "size": 7959,
          "sha512": "0062351c9f6ece45049dfba0a1304525ca29de42398ab245359e344900c6f8191e04e1bf6880c4c660b79c40602c1ff2c5108749dbe1661fed44100756395b62",
          "sha256": "c8c98c2b9238f936aebd34a42fd1246d16ec63b98f626216bd5dbb79fc8ff062",
          "sha1": "2196e1076f63aacd9e56dfca7bc4d87abfdfc787",
          "md5": "54c9215b8bf1eee649baf096064a9433"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_profile-1.1.1-sources.jar",
          "url": "device_info_plus_profile-1.1.1-sources.jar",
          "size": 3223,
          "sha512": "82caa6318ebc252c974fc553266dc5c8111ddf7d77d48dee7626563991ba795562f5851d586023d10405ff452359d737709ef49a08c2637922056004bc648a41",
          "sha256": "d3c6b272d8b7c1286f18833746f6935bf057da64e24b0cf9e4f1d5f82c077d3c",
          "sha1": "cada60cb44885584d55f6831552d5ac73e46635e",
          "md5": "1a71d6b258b08d2bd7a791a4542cee2d"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_profile-1.1.1-javadoc.jar",
          "url": "device_info_plus_profile-1.1.1-javadoc.jar",
          "size": 260823,
          "sha512": "0ae3c120f38e15e563c18b1b0314d8e14a2b588abaaa82c1fa916048d9e63b1046bcf043666e23ea1681d10eb1e33d2101e6822f541ea84a9c8e82e476e7bb64",
          "sha256": "b700f7174f055126ecc89d265636c463ba3395d9aeed6405a573e682dd311e64",
          "sha1": "22c6aa4dfbecd23e20abde2b12eea510d5ec0e9d",
          "md5": "90833eac5d5e12cedb57d145a4938653"
        }
      ]
    }
  ]
}
