{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust.consentmobilesdk",
    "module": "flutter_debug",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.1.2.aar",
          "url": "flutter_debug-1.1.2.aar",
          "size": 24838336,
          "sha512": "7cea5e638d9e57a41c288595c10ff7a4a6688d719f6ea0e6768bb1b031fedce731d80b7465965ab69a622d53a8bef4c06ad92433d8b06afdec5d3bf1a0cd747f",
          "sha256": "9f665579ae34391f43996bc4817edad5380b33f81c6948307ebec3bd9ed1a08e",
          "sha1": "27436cd67cd44c4d4a95aa1a5e939e769eb492c3",
          "md5": "1e6079edd02c576363884a4e979a1f2b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.1.2.aar",
          "url": "flutter_debug-1.1.2.aar",
          "size": 24838336,
          "sha512": "7cea5e638d9e57a41c288595c10ff7a4a6688d719f6ea0e6768bb1b031fedce731d80b7465965ab69a622d53a8bef4c06ad92433d8b06afdec5d3bf1a0cd747f",
          "sha256": "9f665579ae34391f43996bc4817edad5380b33f81c6948307ebec3bd9ed1a08e",
          "sha1": "27436cd67cd44c4d4a95aa1a5e939e769eb492c3",
          "md5": "1e6079edd02c576363884a4e979a1f2b"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.1.2-sources.jar",
          "url": "flutter_debug-1.1.2-sources.jar",
          "size": 1283,
          "sha512": "9096af4c9f50e404d7af5fef6a618c285c28755cf324a301925474f4f41d66de1911ec65eaeacad6dcee1e8f24d997083af77f3fdee964526462397e5043855f",
          "sha256": "8cf1c8b85b788f7cd8942a12d0bfcacef979a19914a3403385586f7a43556009",
          "sha1": "e00e93aeeb733f8cf82b07799a9fab599e67d03f",
          "md5": "4af78276d48ae8c3487ba6fb7d70f500"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.1.2-javadoc.jar",
          "url": "flutter_debug-1.1.2-javadoc.jar",
          "size": 261619,
          "sha512": "2e13989941a93b14cbee129a5e05c5b59452d2847f3a47547a8b66aa49e65ba58cc5f9c179dffaa9a1394273926e117650a2a14952312acb35e1a942eee80d2c",
          "sha256": "b647a9e8a25778d77dd4c4fd469c3c5d871e9e203df34a95cca137ee0c9da36b",
          "sha1": "9eb2356b5ffad86b6500f0da536eede5346cb223",
          "md5": "0c5bdd1deb2557ffbafe9257891039c1"
        }
      ]
    }
  ]
}
