{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.2.aar",
          "url": "shared_preferences_android_release-1.0.2.aar",
          "size": 107175,
          "sha512": "6a061b0dfbc7b584acdadb56b2cd24f27d123dbca418223eebecc07bf94e49cac32f32e108e08cb415a636271988e47fd493174277c5fbe7998ff6b8b68e660f",
          "sha256": "0a03c05228c2653da2643e20ec8f3a3afe0881430edda4e5b62400f4df151a36",
          "sha1": "f340c9621b8b91e0bb873664ffa3ffb6383fd21a",
          "md5": "952806b42a0ed8820494d66905432263"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.2.aar",
          "url": "shared_preferences_android_release-1.0.2.aar",
          "size": 107175,
          "sha512": "6a061b0dfbc7b584acdadb56b2cd24f27d123dbca418223eebecc07bf94e49cac32f32e108e08cb415a636271988e47fd493174277c5fbe7998ff6b8b68e660f",
          "sha256": "0a03c05228c2653da2643e20ec8f3a3afe0881430edda4e5b62400f4df151a36",
          "sha1": "f340c9621b8b91e0bb873664ffa3ffb6383fd21a",
          "md5": "952806b42a0ed8820494d66905432263"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.2-sources.jar",
          "url": "shared_preferences_android_release-1.0.2-sources.jar",
          "size": 13492,
          "sha512": "0377f133f27b75dad7d481bd64c572188345c170cc06df6b1eee48f43f484eaa8f2c8f11b5bef9d4619fe58f13f5af435ecb61ffcd5ac8f2907138e4062a5370",
          "sha256": "04855ff04ad7b1cab4ff55a1c032f4ad03d2c6cdac874cd77a52bfcd84be28f0",
          "sha1": "016b78521fecb132c60d480ffe43b678f71cb7d3",
          "md5": "faf6c46c05c5f8735e1343e903bb5c4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.2-javadoc.jar",
          "url": "shared_preferences_android_release-1.0.2-javadoc.jar",
          "size": 356152,
          "sha512": "6d2cf62163c0aa9718eb88d28d81a3c2826656a69ed6d18df0f5822e21fb62908d62290ba6890f9429b180cb3c79bb99297c6e0399a45e69cf7b79cbd6dbe891",
          "sha256": "dcc28d2791fa11ab34fb32322ed26d411bc8eec78cb147bf119d2a9bce8b8939",
          "sha1": "f58e5d55cb6320bd22a8692f72a58c67bc8fddb2",
          "md5": "cee42dc74c59a7de95ef5d9b47ef10f5"
        }
      ]
    }
  ]
}
