{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust",
    "module": "go-trust-sdk-android",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.1.aar",
          "url": "go-trust-sdk-android-1.0.1.aar",
          "size": 1114815,
          "sha512": "20a7734a8336a981b26437191c15f6910dda52898e12b87586434a9a0528bf4a5dc0dbbb6f3a94e539b4a72a1de2328ea00bea9a23caa487b41f40173c7718e4",
          "sha256": "4d426685462a28284d168cdeb4739db0ec628e7f932981738ab85e272c3bbb46",
          "sha1": "235a59946fc62acf98d74dc6c49ced281307e478",
          "md5": "d56f5ed9494f3c5c77849d7c041500d0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.1.aar",
          "url": "go-trust-sdk-android-1.0.1.aar",
          "size": 1114815,
          "sha512": "20a7734a8336a981b26437191c15f6910dda52898e12b87586434a9a0528bf4a5dc0dbbb6f3a94e539b4a72a1de2328ea00bea9a23caa487b41f40173c7718e4",
          "sha256": "4d426685462a28284d168cdeb4739db0ec628e7f932981738ab85e272c3bbb46",
          "sha1": "235a59946fc62acf98d74dc6c49ced281307e478",
          "md5": "d56f5ed9494f3c5c77849d7c041500d0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.1-sources.jar",
          "url": "go-trust-sdk-android-1.0.1-sources.jar",
          "size": 212637,
          "sha512": "547adef562cf6d9d1b5d968d71a56950f39b0365e1e5c3efa32bf178c2386b9e021bc1d37a657501703701d01bc4e1f8746e7719ce452bd3e5f5db3516fb531a",
          "sha256": "c546269cf79280693cb4d1c8c2f6f005712ebece63941f4b8131eb0907646350",
          "sha1": "3e8f28b66cf503a7506544c11e74b22620cef970",
          "md5": "1e983765478cb77cc20b9c7f9453eaf0"
        }
      ]
    }
  ]
}
