{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.2.aar",
          "url": "device_info_plus_debug-1.0.2.aar",
          "size": 7941,
          "sha512": "53773345373d285209a9a64632f84e12125e1f0ff0a6fb09a34b0d0c084b537fa3fc85c1ba5c3da4f4c8ac68851abc36e72ee7328c011bc1c2de8a9b36e7b7da",
          "sha256": "de33141347b92c788b3488ff1c5d40974147670629c73adb9415dbbce3f79b26",
          "sha1": "be55ec1888ac443f51a22f382babed8ebd8d6f52",
          "md5": "28e4e27d949f40e1b38bdf6c314b09ba"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.2.aar",
          "url": "device_info_plus_debug-1.0.2.aar",
          "size": 7941,
          "sha512": "53773345373d285209a9a64632f84e12125e1f0ff0a6fb09a34b0d0c084b537fa3fc85c1ba5c3da4f4c8ac68851abc36e72ee7328c011bc1c2de8a9b36e7b7da",
          "sha256": "de33141347b92c788b3488ff1c5d40974147670629c73adb9415dbbce3f79b26",
          "sha1": "be55ec1888ac443f51a22f382babed8ebd8d6f52",
          "md5": "28e4e27d949f40e1b38bdf6c314b09ba"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_debug-1.0.2-sources.jar",
          "url": "device_info_plus_debug-1.0.2-sources.jar",
          "size": 3223,
          "sha512": "82caa6318ebc252c974fc553266dc5c8111ddf7d77d48dee7626563991ba795562f5851d586023d10405ff452359d737709ef49a08c2637922056004bc648a41",
          "sha256": "d3c6b272d8b7c1286f18833746f6935bf057da64e24b0cf9e4f1d5f82c077d3c",
          "sha1": "cada60cb44885584d55f6831552d5ac73e46635e",
          "md5": "1a71d6b258b08d2bd7a791a4542cee2d"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_debug-1.0.2-javadoc.jar",
          "url": "device_info_plus_debug-1.0.2-javadoc.jar",
          "size": 260826,
          "sha512": "f269a2a882e533b48d70ec9be47f2935967d1d10b6ae42c8f8b6a88e5d046414ac7e1ed2fad3b13ce6ad33b0b3ed726818ccae6cdfd7840d3fa1cc433d486baa",
          "sha256": "1a00233eda468a31dd93431de431dd7a3eec8617cabadbb439cf00312504bd99",
          "sha1": "ad9420cc9efadb6158719741a44482b169e807fc",
          "md5": "35e08ebaf3f01b8a54db7ff9a9242476"
        }
      ]
    }
  ]
}
