{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.3.aar",
          "url": "webview_flutter_android_profile-1.0.3.aar",
          "size": 280986,
          "sha512": "45b6ce4b339eff1560914bedc85957b523e3314db164a1ef6cb335a3b5067b0205ed8743d4b815ffd5a31d587bad74119691797997ed50d07d59cf6cfb130a29",
          "sha256": "9df9eac164f217da3c8870d846b0b6e0189e44eed04f4c6b85ecfc9b76bdd5f5",
          "sha1": "9a293ff92f211fae04921dcad3e47f0f34bcce1d",
          "md5": "8cd91c628dfc97425899d91d04623b7f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.3.aar",
          "url": "webview_flutter_android_profile-1.0.3.aar",
          "size": 280986,
          "sha512": "45b6ce4b339eff1560914bedc85957b523e3314db164a1ef6cb335a3b5067b0205ed8743d4b815ffd5a31d587bad74119691797997ed50d07d59cf6cfb130a29",
          "sha256": "9df9eac164f217da3c8870d846b0b6e0189e44eed04f4c6b85ecfc9b76bdd5f5",
          "sha1": "9a293ff92f211fae04921dcad3e47f0f34bcce1d",
          "md5": "8cd91c628dfc97425899d91d04623b7f"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.3-sources.jar",
          "url": "webview_flutter_android_profile-1.0.3-sources.jar",
          "size": 61256,
          "sha512": "e3db1dce34c386ce779888a190e84c5f72e7dd021cacb1f763168532618a880d7ff0ee468906838adb7e42014874c9ba4f9242269b5490489992edb597961436",
          "sha256": "00584e3f73376120584215cc456a80948d2d9e252aa9b1af928063244eae7c0d",
          "sha1": "aa4fb2c895a8a19e0caae6d391614eba954d2d9c",
          "md5": "2fed686b26cea8a297d9479369d5867a"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.3-javadoc.jar",
          "url": "webview_flutter_android_profile-1.0.3-javadoc.jar",
          "size": 750484,
          "sha512": "e8711a74308cdd18bafa65cb20affd01ec531c942e60f276a65c2b773db3e8f8a521cc33628dd318d2352e1dde35806f63ff5b686daee3021d2213abbebd9b7d",
          "sha256": "19f3ee469a4a22cc4eb6360d4e56daa71f13f306755091426c6b10a5f646047b",
          "sha1": "bd48adcce6e39c14992997566f96e6a97af5324e",
          "md5": "77c694dc2a54c2bde3c9e944fb42ce31"
        }
      ]
    }
  ]
}
