{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust",
    "module": "go-trust-sdk-android-tv",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.gotrust",
          "module": "go-trust-sdk-android",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-tv-1.0.4.aar",
          "url": "go-trust-sdk-android-tv-1.0.4.aar",
          "size": 532180,
          "sha512": "c203873e551cc57618bf6c159bfbd4c475ca6c2551b92a303cc98015e97cddf830f0ee9d3f16c906b1857a2f9c6fee697c46bd4c482241179709c8421ddcbc97",
          "sha256": "bafb4c3de53d32deabab4a5f3aea3c05e0d325b7f0a9e82890cbffa07b0deeda",
          "sha1": "854a4bb44a6229b82c0fbc259abc09c552b6fe02",
          "md5": "d63f2c7a32fd5ee7a421e9e13cbadafa"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "com.gotrust",
          "module": "go-trust-sdk-android",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-tv-1.0.4.aar",
          "url": "go-trust-sdk-android-tv-1.0.4.aar",
          "size": 532180,
          "sha512": "c203873e551cc57618bf6c159bfbd4c475ca6c2551b92a303cc98015e97cddf830f0ee9d3f16c906b1857a2f9c6fee697c46bd4c482241179709c8421ddcbc97",
          "sha256": "bafb4c3de53d32deabab4a5f3aea3c05e0d325b7f0a9e82890cbffa07b0deeda",
          "sha1": "854a4bb44a6229b82c0fbc259abc09c552b6fe02",
          "md5": "d63f2c7a32fd5ee7a421e9e13cbadafa"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "go-trust-sdk-android-tv-1.0.4-sources.jar",
          "url": "go-trust-sdk-android-tv-1.0.4-sources.jar",
          "size": 103307,
          "sha512": "88c04b243dcaf838c47453b826e0d0df55c60f3584928d551d87999977b57bee7c40210e858586b0bf2d087eb38b2ee9dd976d7feb139eb2c2ae81a8a45bd29a",
          "sha256": "6a6b0cf7b039d942d9fc8c79e643d0de12977a51b7efdcb7a74eb0b55f58dd23",
          "sha1": "0b3ee3a81bead68ffdc454b6faafc81e9b99e181",
          "md5": "b69b7dc0a8a529ac04763337378cbb2f"
        }
      ]
    }
  ]
}
