{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_release",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.4.aar",
          "url": "file_picker_release-1.0.4.aar",
          "size": 40195,
          "sha512": "164e5c679fd2f9fdb1a621d4ec71c060d703d2f1d62e54ffd6cb3c74ec1f68ff5cf7f4722a66a30a646b14e3b7023dbd8b4058a9a674d877370e36217f0d9978",
          "sha256": "70e26966787d4d4eed779f561a4417a9093cc2f7fc8c55e05ee6af08cf7a04d8",
          "sha1": "1d4e9c28f5cd7d9f7d0bcb0f52a2bc12e0808890",
          "md5": "a1abd618e8c17191bc51831889ed20b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.4.aar",
          "url": "file_picker_release-1.0.4.aar",
          "size": 40195,
          "sha512": "164e5c679fd2f9fdb1a621d4ec71c060d703d2f1d62e54ffd6cb3c74ec1f68ff5cf7f4722a66a30a646b14e3b7023dbd8b4058a9a674d877370e36217f0d9978",
          "sha256": "70e26966787d4d4eed779f561a4417a9093cc2f7fc8c55e05ee6af08cf7a04d8",
          "sha1": "1d4e9c28f5cd7d9f7d0bcb0f52a2bc12e0808890",
          "md5": "a1abd618e8c17191bc51831889ed20b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_release-1.0.4-sources.jar",
          "url": "file_picker_release-1.0.4-sources.jar",
          "size": 11292,
          "sha512": "6934d3e4ab9146e349471a11c4f53b19c742f677cc6686d21de93fc497534f73274b86e3f3ec2303f419ca4cb2638caf9e5782949925841b4aa329b9e5633a95",
          "sha256": "567c8d84a2aa6a6032316f8f491b21a5dcc23ab386f5b0cf333bb277b17db94d",
          "sha1": "050e0893e7be2da532a4ce3159e11ef66b30656a",
          "md5": "e74f61a98f12b510bc51302606a05d86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_release-1.0.4-javadoc.jar",
          "url": "file_picker_release-1.0.4-javadoc.jar",
          "size": 307531,
          "sha512": "e20c16be24044cba1340da2d73e172df11149cad81c8889f6348becf78c4c33f3e5aea8f515bc78ff667af78e5702292897216478b36548ac3c6ad49c0bf2cea",
          "sha256": "35bc3b116ae3b9ee7251b37eaf1d9b5c8767e51fe39153be1fc2a91bf0c76b47",
          "sha1": "e7b00f14a729e0d2b47ff1f5b46cd1e77aefea7e",
          "md5": "78e71195772ba7cd40232e92acef12e9"
        }
      ]
    }
  ]
}
