{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.9.aar",
          "url": "device_info_plus_profile-1.0.9.aar",
          "size": 7959,
          "sha512": "0062351c9f6ece45049dfba0a1304525ca29de42398ab245359e344900c6f8191e04e1bf6880c4c660b79c40602c1ff2c5108749dbe1661fed44100756395b62",
          "sha256": "c8c98c2b9238f936aebd34a42fd1246d16ec63b98f626216bd5dbb79fc8ff062",
          "sha1": "2196e1076f63aacd9e56dfca7bc4d87abfdfc787",
          "md5": "54c9215b8bf1eee649baf096064a9433"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.9.aar",
          "url": "device_info_plus_profile-1.0.9.aar",
          "size": 7959,
          "sha512": "0062351c9f6ece45049dfba0a1304525ca29de42398ab245359e344900c6f8191e04e1bf6880c4c660b79c40602c1ff2c5108749dbe1661fed44100756395b62",
          "sha256": "c8c98c2b9238f936aebd34a42fd1246d16ec63b98f626216bd5dbb79fc8ff062",
          "sha1": "2196e1076f63aacd9e56dfca7bc4d87abfdfc787",
          "md5": "54c9215b8bf1eee649baf096064a9433"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_profile-1.0.9-sources.jar",
          "url": "device_info_plus_profile-1.0.9-sources.jar",
          "size": 3223,
          "sha512": "82caa6318ebc252c974fc553266dc5c8111ddf7d77d48dee7626563991ba795562f5851d586023d10405ff452359d737709ef49a08c2637922056004bc648a41",
          "sha256": "d3c6b272d8b7c1286f18833746f6935bf057da64e24b0cf9e4f1d5f82c077d3c",
          "sha1": "cada60cb44885584d55f6831552d5ac73e46635e",
          "md5": "1a71d6b258b08d2bd7a791a4542cee2d"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_profile-1.0.9-javadoc.jar",
          "url": "device_info_plus_profile-1.0.9-javadoc.jar",
          "size": 260828,
          "sha512": "da32b7d23880e1162c65ccce2571cd61b39ece091681425d334f216b0f4030b2d04735c82ae3632780c56c25ff260b3d0aa793359843b4861ee06eb56c982cb8",
          "sha256": "5b7c5c87eb5359f6ff25af4e7e54316c191e3075454733bbf78bbfc78243ca7d",
          "sha1": "81d13f2222a198e388f5e0c24367f5d52ccefd29",
          "md5": "1c5252de0735cfbc3943c4a4208db505"
        }
      ]
    }
  ]
}
