{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_profile",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.1.2.aar",
          "url": "shared_preferences_android_profile-1.1.2.aar",
          "size": 114400,
          "sha512": "d8b99666a0a309f3fffd797f4b14ef12786ff4247e5626dffb0205cff90e63b180777fd5e258f7db04df55fa642428fcc51dcf73d355e13b8397d4622304860c",
          "sha256": "78c983812495891c133a15d70cb297e996d9a04707c0f135dc927cb75f462a2b",
          "sha1": "444f84a4f49e3482c659ea8be7cc991e4f185233",
          "md5": "a67ed4b794c180308f2ea6fad2f65e81"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.1.2.aar",
          "url": "shared_preferences_android_profile-1.1.2.aar",
          "size": 114400,
          "sha512": "d8b99666a0a309f3fffd797f4b14ef12786ff4247e5626dffb0205cff90e63b180777fd5e258f7db04df55fa642428fcc51dcf73d355e13b8397d4622304860c",
          "sha256": "78c983812495891c133a15d70cb297e996d9a04707c0f135dc927cb75f462a2b",
          "sha1": "444f84a4f49e3482c659ea8be7cc991e4f185233",
          "md5": "a67ed4b794c180308f2ea6fad2f65e81"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.1.2-sources.jar",
          "url": "shared_preferences_android_profile-1.1.2-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.1.2-javadoc.jar",
          "url": "shared_preferences_android_profile-1.1.2-javadoc.jar",
          "size": 358408,
          "sha512": "f9c2df92f870117b5ae20b4076ef0f3a9e37ee484c1483130293d013fd68be300d0ba7ea581bb964fa4c50fd490753b5655e92ee75623a4cbd79c48741aa2b9a",
          "sha256": "080d05a5d763622a6a5133bc9b0c58415a9ea8831f1786d43ff5d85047f50b90",
          "sha1": "c90e3abf16bceef4f5b41ae4827a274446871816",
          "md5": "39be4681650aee0e04728b0ab115dc46"
        }
      ]
    }
  ]
}
