{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_profile",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.4.aar",
          "url": "shared_preferences_android_profile-1.0.4.aar",
          "size": 114400,
          "sha512": "d8b99666a0a309f3fffd797f4b14ef12786ff4247e5626dffb0205cff90e63b180777fd5e258f7db04df55fa642428fcc51dcf73d355e13b8397d4622304860c",
          "sha256": "78c983812495891c133a15d70cb297e996d9a04707c0f135dc927cb75f462a2b",
          "sha1": "444f84a4f49e3482c659ea8be7cc991e4f185233",
          "md5": "a67ed4b794c180308f2ea6fad2f65e81"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.4.aar",
          "url": "shared_preferences_android_profile-1.0.4.aar",
          "size": 114400,
          "sha512": "d8b99666a0a309f3fffd797f4b14ef12786ff4247e5626dffb0205cff90e63b180777fd5e258f7db04df55fa642428fcc51dcf73d355e13b8397d4622304860c",
          "sha256": "78c983812495891c133a15d70cb297e996d9a04707c0f135dc927cb75f462a2b",
          "sha1": "444f84a4f49e3482c659ea8be7cc991e4f185233",
          "md5": "a67ed4b794c180308f2ea6fad2f65e81"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.4-sources.jar",
          "url": "shared_preferences_android_profile-1.0.4-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.4-javadoc.jar",
          "url": "shared_preferences_android_profile-1.0.4-javadoc.jar",
          "size": 358428,
          "sha512": "76caab4cd273290b13bbe6fbc3533e904ead60d4608840acc01c61427596d04b97363ba932c7078c24548bd243e87bb2796f769cd7da4695ae046240d37d38e0",
          "sha256": "2feb9a0009f073829881eee874f2bff2f9c51a95060938714733b1f282a68310",
          "sha1": "865bd3db1fd6bd93c71d2b8abe5cbbbeea9fc954",
          "md5": "3a4236ad9b95552c7635ebaf5e104385"
        }
      ]
    }
  ]
}
