{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.6.aar",
          "url": "webview_flutter_android_release-1.0.6.aar",
          "size": 266950,
          "sha512": "950027e847d7ca06dafb2ab94601dfa7f49fa012d63d900e53fd58166e53044a634b3fe3148b85816b08d4233a1786d0fd9f925c94210dcd81c448638529c9e2",
          "sha256": "3b0bb5033f3f546448220fe2cbc4b1fc1890c758dbb02ba35a9372d5c4ae53a9",
          "sha1": "68e0596d182404000b621e7d4c457deaa80c9280",
          "md5": "929970d84d46537f05391871b15b783f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.6.aar",
          "url": "webview_flutter_android_release-1.0.6.aar",
          "size": 266950,
          "sha512": "950027e847d7ca06dafb2ab94601dfa7f49fa012d63d900e53fd58166e53044a634b3fe3148b85816b08d4233a1786d0fd9f925c94210dcd81c448638529c9e2",
          "sha256": "3b0bb5033f3f546448220fe2cbc4b1fc1890c758dbb02ba35a9372d5c4ae53a9",
          "sha1": "68e0596d182404000b621e7d4c457deaa80c9280",
          "md5": "929970d84d46537f05391871b15b783f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.6-sources.jar",
          "url": "webview_flutter_android_release-1.0.6-sources.jar",
          "size": 61506,
          "sha512": "e6568ae0bc08aa93f82969eb5163670b978aa0ce9d7afad819121949388a63e6250769aff10c8aa49cb75695eb40e109a95339bf591b3c1670de27e43728cd63",
          "sha256": "89a1b253e75696a2014ff86d66e8be4957a953a2dffdc90208065efbfe52ab76",
          "sha1": "d84f5919cb52a89638e6a5bf8e86171f7b40c9e4",
          "md5": "1afcd4ba8b50bfed2f5ca86d4a89f702"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.6-javadoc.jar",
          "url": "webview_flutter_android_release-1.0.6-javadoc.jar",
          "size": 750995,
          "sha512": "8334e7c37243139f962d541efe3487f79b4115a8618490a873d969cf20be9dc2adbb4a400218da8a3d2e45b57002cd4b7fd80e5c875ed1662664be70d4ccaabd",
          "sha256": "ec88a6f964e5f4ab33ecadaa3b555a45f8ac7c9db003b12e7d849376841ce946",
          "sha1": "2dade87f071c1e9e173c7e03d3ef540ac0854cbb",
          "md5": "0000dba75290382df1531b47d7f2bb6c"
        }
      ]
    }
  ]
}
