{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.1.0.aar",
          "url": "webview_flutter_android_release-1.1.0.aar",
          "size": 266950,
          "sha512": "950027e847d7ca06dafb2ab94601dfa7f49fa012d63d900e53fd58166e53044a634b3fe3148b85816b08d4233a1786d0fd9f925c94210dcd81c448638529c9e2",
          "sha256": "3b0bb5033f3f546448220fe2cbc4b1fc1890c758dbb02ba35a9372d5c4ae53a9",
          "sha1": "68e0596d182404000b621e7d4c457deaa80c9280",
          "md5": "929970d84d46537f05391871b15b783f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.1.0.aar",
          "url": "webview_flutter_android_release-1.1.0.aar",
          "size": 266950,
          "sha512": "950027e847d7ca06dafb2ab94601dfa7f49fa012d63d900e53fd58166e53044a634b3fe3148b85816b08d4233a1786d0fd9f925c94210dcd81c448638529c9e2",
          "sha256": "3b0bb5033f3f546448220fe2cbc4b1fc1890c758dbb02ba35a9372d5c4ae53a9",
          "sha1": "68e0596d182404000b621e7d4c457deaa80c9280",
          "md5": "929970d84d46537f05391871b15b783f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.1.0-sources.jar",
          "url": "webview_flutter_android_release-1.1.0-sources.jar",
          "size": 61506,
          "sha512": "e6568ae0bc08aa93f82969eb5163670b978aa0ce9d7afad819121949388a63e6250769aff10c8aa49cb75695eb40e109a95339bf591b3c1670de27e43728cd63",
          "sha256": "89a1b253e75696a2014ff86d66e8be4957a953a2dffdc90208065efbfe52ab76",
          "sha1": "d84f5919cb52a89638e6a5bf8e86171f7b40c9e4",
          "md5": "1afcd4ba8b50bfed2f5ca86d4a89f702"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.1.0-javadoc.jar",
          "url": "webview_flutter_android_release-1.1.0-javadoc.jar",
          "size": 750887,
          "sha512": "a2cbd9847d855ed71e53b48d24a73488901d919ebb5fc52f1ef4779354663f6df6c115a82164fb81513a397f2185bd70a50df2f2666d8bc34540c524e9bdade6",
          "sha256": "15a0addbb75a87ce69fb81ea2c635d3bc0ab7fab31bc69847ae01b7d63dbe056",
          "sha1": "b2672a0625bc938559b86fbb1dbe48484da09bd4",
          "md5": "d82e934e799e7d535c1347532aea1153"
        }
      ]
    }
  ]
}
