{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gotrust",
    "module": "go-trust-sdk-android",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.3.aar",
          "url": "go-trust-sdk-android-1.0.3.aar",
          "size": 1371426,
          "sha512": "3c1df4c9bd377c8e603ef22518a81bb6383c4a11c87cc8ce734b9de5ff1e5c573a9957c3dee27bd9bf44f1c3edd88bd5d86107384250009fab3044680f0b1bd5",
          "sha256": "a013a199a531d232de2c6bc9ac5b312036285e122e731e4ca624f338ac0ed2a1",
          "sha1": "b400ace0af7c358b0f52eda164333f2c44ec7d64",
          "md5": "42cb6f9c864f9614e019a9447d20bb9f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.3.aar",
          "url": "go-trust-sdk-android-1.0.3.aar",
          "size": 1371426,
          "sha512": "3c1df4c9bd377c8e603ef22518a81bb6383c4a11c87cc8ce734b9de5ff1e5c573a9957c3dee27bd9bf44f1c3edd88bd5d86107384250009fab3044680f0b1bd5",
          "sha256": "a013a199a531d232de2c6bc9ac5b312036285e122e731e4ca624f338ac0ed2a1",
          "sha1": "b400ace0af7c358b0f52eda164333f2c44ec7d64",
          "md5": "42cb6f9c864f9614e019a9447d20bb9f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "go-trust-sdk-android-1.0.3-sources.jar",
          "url": "go-trust-sdk-android-1.0.3-sources.jar",
          "size": 257589,
          "sha512": "df3a893db4bb6be4c5d5cf5fbdeb0c4c89c2ecf3f8cf9cac5ffa294b0b6b33e5522b56874c184d474e69d5c95269b118142f081fdf7e82dd57b50ac914f41223",
          "sha256": "cb7f44c897fbf6e1269a6a457db3bfd86c3f3f5e973f3e64c2bbded9de662e41",
          "sha1": "41277b53dce05eb95f449c4fc4d6a805b7c87354",
          "md5": "0ebf07b102bafbfe15632d02af0fd840"
        }
      ]
    }
  ]
}
