{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_release",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.3.aar",
          "url": "file_picker_release-1.0.3.aar",
          "size": 40195,
          "sha512": "164e5c679fd2f9fdb1a621d4ec71c060d703d2f1d62e54ffd6cb3c74ec1f68ff5cf7f4722a66a30a646b14e3b7023dbd8b4058a9a674d877370e36217f0d9978",
          "sha256": "70e26966787d4d4eed779f561a4417a9093cc2f7fc8c55e05ee6af08cf7a04d8",
          "sha1": "1d4e9c28f5cd7d9f7d0bcb0f52a2bc12e0808890",
          "md5": "a1abd618e8c17191bc51831889ed20b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.3.aar",
          "url": "file_picker_release-1.0.3.aar",
          "size": 40195,
          "sha512": "164e5c679fd2f9fdb1a621d4ec71c060d703d2f1d62e54ffd6cb3c74ec1f68ff5cf7f4722a66a30a646b14e3b7023dbd8b4058a9a674d877370e36217f0d9978",
          "sha256": "70e26966787d4d4eed779f561a4417a9093cc2f7fc8c55e05ee6af08cf7a04d8",
          "sha1": "1d4e9c28f5cd7d9f7d0bcb0f52a2bc12e0808890",
          "md5": "a1abd618e8c17191bc51831889ed20b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_release-1.0.3-sources.jar",
          "url": "file_picker_release-1.0.3-sources.jar",
          "size": 11292,
          "sha512": "6934d3e4ab9146e349471a11c4f53b19c742f677cc6686d21de93fc497534f73274b86e3f3ec2303f419ca4cb2638caf9e5782949925841b4aa329b9e5633a95",
          "sha256": "567c8d84a2aa6a6032316f8f491b21a5dcc23ab386f5b0cf333bb277b17db94d",
          "sha1": "050e0893e7be2da532a4ce3159e11ef66b30656a",
          "md5": "e74f61a98f12b510bc51302606a05d86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "file_picker_release-1.0.3-javadoc.jar",
          "url": "file_picker_release-1.0.3-javadoc.jar",
          "size": 307526,
          "sha512": "7ba0c995b065de1b46794acf8736940673b453366392725baa74be11e7bd9939589160a088ebf87fe16c9535a815279820af15e13c66d293a1491af0978d9eab",
          "sha256": "e62199a609938e65e762e24f76f31572d28ee9e6bfbfe53231fba0b96ea03b3f",
          "sha1": "ef6b65c257008de99a5c0534cc029174002a2754",
          "md5": "6aad6b9f7dca7a9a7016dd809503b9b9"
        }
      ]
    }
  ]
}
