{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_debug",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.1.1.aar",
          "url": "webview_flutter_android_debug-1.1.1.aar",
          "size": 281328,
          "sha512": "a84372757a85296904ac041953a258c7b5d654b3d7f9266723544104dcb6b53195b893a097e0052fbbf34e0d58bb3a7c9b0dbf1b91b689c156de5ea2ce5152c8",
          "sha256": "f8252f5352b7b69ea4ac5a7bb69838e87e22a302ae9a8503c0a00998763b79b3",
          "sha1": "8e23379d95b551759c24e832b554e5c5f81e3b89",
          "md5": "720dde71116b86872146a3a7e5723c1b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.1.1.aar",
          "url": "webview_flutter_android_debug-1.1.1.aar",
          "size": 281328,
          "sha512": "a84372757a85296904ac041953a258c7b5d654b3d7f9266723544104dcb6b53195b893a097e0052fbbf34e0d58bb3a7c9b0dbf1b91b689c156de5ea2ce5152c8",
          "sha256": "f8252f5352b7b69ea4ac5a7bb69838e87e22a302ae9a8503c0a00998763b79b3",
          "sha1": "8e23379d95b551759c24e832b554e5c5f81e3b89",
          "md5": "720dde71116b86872146a3a7e5723c1b"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_debug-1.1.1-sources.jar",
          "url": "webview_flutter_android_debug-1.1.1-sources.jar",
          "size": 61506,
          "sha512": "e6568ae0bc08aa93f82969eb5163670b978aa0ce9d7afad819121949388a63e6250769aff10c8aa49cb75695eb40e109a95339bf591b3c1670de27e43728cd63",
          "sha256": "89a1b253e75696a2014ff86d66e8be4957a953a2dffdc90208065efbfe52ab76",
          "sha1": "d84f5919cb52a89638e6a5bf8e86171f7b40c9e4",
          "md5": "1afcd4ba8b50bfed2f5ca86d4a89f702"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_debug-1.1.1-javadoc.jar",
          "url": "webview_flutter_android_debug-1.1.1-javadoc.jar",
          "size": 750761,
          "sha512": "4ef7a93a1bf38b0a91e44e498616d4c22d8de830b609a51e48850bd905ba89f0432d78282daa8836e72b5a39fd3d43ca49db44d41450fe5cd30fa6ac2468e646",
          "sha256": "d06fc2dab51640165072316dfdd44614e789af401d387b4b35bfd6111e9a6fd0",
          "sha1": "b2ad10052c2b3487f8a65f1384ca0f4d521701a8",
          "md5": "eabeebfa217f136943c5545988a81a99"
        }
      ]
    }
  ]
}
